#!/bin/bash

# Create scripts directory if it doesn't exist
mkdir -p scripts

# Define the output file
INDEX_FILE="src/index.ts"

# Clear the existing index file
cat > $INDEX_FILE << EOL
// This file is auto-generated by scripts/generate-indexes.sh
// Do not edit this file directly

EOL

# Find all TypeScript files in the src directory and subdirectories, excluding the index.ts file itself and test files
# Use a single find command and store the results to avoid multiple file system traversals
FILES=$(find src -type f -name "*.ts" -not -path "*/index.ts" -not -path "*/*.test.ts" -not -path "*/__tests__/*" | sort)

# Create a temporary file for building the index content
TMP_INDEX=$(mktemp)

# First, export all modules that don't have default exports
echo "// Export all modules" >> $TMP_INDEX
for file in $FILES; do
  # Extract the relative path from src
  rel_path=${file#src/}
  # Extract the directory path if any
  dir_path=$(dirname "$rel_path")
  # Extract the filename without extension
  filename=$(basename "$rel_path" .ts)
  
  # Skip the index file itself
  if [ "$filename" != "index" ]; then
    # Check if the file has any named exports (not just a default export)
    if grep -q "export " "$file" | grep -v "export default"; then
      # If the file is directly in src, use simple path
      if [ "$dir_path" = "." ]; then
        echo "export * from './$filename';" >> $TMP_INDEX
      else
        # For nested files, create the import path
        echo "export * from './$dir_path/$filename';" >> $TMP_INDEX
      fi
    fi
  fi
done

echo "" >> $TMP_INDEX

# Then, export default classes
echo "// Export default classes" >> $TMP_INDEX
for file in $FILES; do
  # Extract the relative path from src
  rel_path=${file#src/}
  # Extract the directory path if any
  dir_path=$(dirname "$rel_path")
  # Extract the filename without extension
  filename=$(basename "$rel_path" .ts)
  
  # Skip the index file itself
  if [ "$filename" != "index" ]; then
    # Check if the file has a default export
    if grep -q "export default" "$file"; then
      # Use the filename with first letter capitalized and replace dots with underscores
      capitalized=$(echo "$filename" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/\./_/g')
      
      # If the file is directly in src, use simple path
      if [ "$dir_path" = "." ]; then
        echo "export { default as $capitalized } from './$filename';" >> $TMP_INDEX
      else
        # For nested files, create the import path with directory prefix to avoid naming conflicts
        # For example, router/router.ts becomes RouterRouter instead of Router
        dir_capitalized=$(echo "$dir_path" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/\./_/g')
        echo "export { default as $dir_capitalized$capitalized } from './$dir_path/$filename';" >> $TMP_INDEX
      fi
    fi
  fi
done

echo "" >> $TMP_INDEX

# Dynamically find and re-export constants and enums for backward compatibility
echo "// Re-export specific items for backward compatibility" >> $TMP_INDEX

# Process each file once to extract both constants and enums
for file in $FILES; do
  # Extract the relative path from src
  rel_path=${file#src/}
  # Extract the directory path if any
  dir_path=$(dirname "$rel_path")
  # Extract the filename without extension
  filename=$(basename "$rel_path" .ts)
  
  # Skip the index file itself
  if [ "$filename" != "index" ]; then
    # Use grep with -E to combine patterns and reduce file reads
    exports=$(grep -E "export (const|enum) [A-Z][A-Z0-9_]*" "$file" | sed -E 's/export (const|enum) ([A-Z][A-Z0-9_]*).*/\2/')
    
    if [ ! -z "$exports" ]; then
      # Create a comma-separated list of exports
      exports_list=$(echo "$exports" | tr '\n' ',' | sed 's/,$//')
      
      # If the file is directly in src, use simple path
      if [ "$dir_path" = "." ]; then
        echo "export { $exports_list } from './$filename';" >> $TMP_INDEX
      else
        # For nested files, create the import path
        echo "export { $exports_list } from './$dir_path/$filename';" >> $TMP_INDEX
      fi
    fi
  fi
done

# Now, create barrel exports for each subdirectory
echo "" >> $TMP_INDEX
echo "// Barrel exports for subdirectories" >> $TMP_INDEX

# Find all subdirectories in src in a single command
SUBDIRS=$(find src -type d -not -path "src" -not -path "src/__tests__*" | sort)

for subdir in $SUBDIRS; do
  # Get the directory name relative to src
  rel_dir=${subdir#src/}
  # Capitalize the first letter of the directory name for the namespace
  namespace=$(echo "$rel_dir" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')
  
  # Check if there are any TypeScript files in this directory
  SUBDIR_FILES=$(find "$subdir" -maxdepth 1 -name "*.ts" -not -name "*.test.ts" -not -name "index.ts")
  
  if [ -n "$SUBDIR_FILES" ]; then
    echo "// Create module for $rel_dir" >> $TMP_INDEX
    echo "import * as ${namespace}Module from './$rel_dir';" >> $TMP_INDEX
    echo "export { ${namespace}Module as $namespace };" >> $TMP_INDEX
    echo "" >> $TMP_INDEX
    
    # Create a barrel file for this subdirectory
    SUBDIR_INDEX="${subdir}/index.ts"
    
    # Create the subdirectory index file in one go
    cat > $SUBDIR_INDEX << EOL
// This file is auto-generated by scripts/generate-indexes.sh
// Do not edit this file directly

EOL
    
    # Export all modules from this directory
    for file in $SUBDIR_FILES; do
      filename=$(basename "$file" .ts)
      
      # Export all named exports
      echo "export * from './$filename';" >> $SUBDIR_INDEX
      
      # Check if the file has a default export and export it with a specific name
      if grep -q "export default" "$file"; then
        # Replace dots with underscores in the capitalized name
        capitalized=$(echo "$filename" | awk '{print toupper(substr($0,1,1)) substr($0,2)}' | sed 's/\./_/g')
        echo "export { default as $capitalized } from './$filename';" >> $SUBDIR_INDEX
      fi
    done
  fi
done

# Move the temporary file to the final location
cat $TMP_INDEX >> $INDEX_FILE
rm $TMP_INDEX

echo "Index file generated successfully at $INDEX_FILE" 